replicaCount: 1

image:
  backend:
    repository: "your-registry-or-local/your-backend-image"
    tag: "14536923939"
    pullPolicy: IfNotPresent
  frontend:
    repository: "your-registry-or-local/your-frontend-image"
    tag: "14536923939"
    pullPolicy: IfNotPresent

service:
  backend:
    type: ClusterIP
    port: 5000
  frontend:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: study-companion.local
      paths:
        - /
