apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: study-companion-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yourusername/study-companion-app.git'
    targetRevision: HEAD
    path: infra/k8s/overlays/eks  # Use "local" for local testing
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: study-companion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
