name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend dependencies
        run: pip install -r app/backend/requirements.txt
      - name: Run backend tests
        run: echo "Running backend tests..."  # Replace with actual tests if available
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: app/backend
          file: Dockerfile
          push: true
          tags: your-dockerhub-username/study-companion-backend:${{ github.run_id }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend dependencies
        working-directory: app/frontend
        run: npm install
      - name: Run frontend tests
        working-directory: app/frontend
        run: echo "Running frontend tests..."  # Replace with actual tests if available
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: app/frontend
          file: Dockerfile
          push: true
          tags: your-dockerhub-username/study-companion-frontend:${{ github.run_id }}

  update-deployment:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Helm chart image tag
        run: |
          # Update the image tag in the Helm values file (adjust the path as needed)
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' infra/helm/study-companion/values.yaml
      - name: Commit and push changes
        run: |
          git config --local user.email "mm3818@srmist.edu.in"
          git config --local user.name "mm3818"
          git add infra/helm/study-companion/values.yaml
          git commit -m "Update image tags to ${{ github.run_id }}"
          git push
