apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: study-companion-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yourusername/Study_Companion.git'
    targetRevision: HEAD
    path: infra/helm/study-companion   # or your k8s overlays directory
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: study-companion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
