apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-companion-frontend
  labels:
    app: study-companion-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-companion-frontend
  template:
    metadata:
      labels:
        app: study-companion-frontend
    spec:
      containers:
      - name: study-companion-frontend
        image: {{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}
        imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
        ports:
        - containerPort: 80
