apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-companion-backend
  labels:
    app: study-companion-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-companion-backend
  template:
    metadata:
      labels:
        app: study-companion-backend
    spec:
      containers:
      - name: study-companion-backend
        image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
        imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
        ports:
        - containerPort: 5000
