name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build-backend:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Backend Directory (Debug)
        run: ls -al app/backend  # This step already exists

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Backend Dependencies
        working-directory: app/backend
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run Backend Tests
        working-directory: app/backend
        run: echo "Running backend tests..."  # Replace with your actual test command
      
      - name: Log in to Docker Hub (Backend)
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List Docker Context (Debug)
        run: ls -al app/backend

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v3
        with:
          context: https://github.com/mm3818/Study_Companion/tree/main/app/backend
          file: Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/study-companion-backend:${{ github.run_id }}

  build-frontend:
    name: Build & Push Frontend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: List Frontend Directory (Debug)
        run: ls -al app/frontend
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Frontend Dependencies
        working-directory: app/frontend
        run: npm install
      
      - name: Run Frontend Tests
        working-directory: app/frontend
        run: echo "Running frontend tests..."  # Replace with your actual test command
      
      - name: Log in to Docker Hub (Frontend)
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v3
        with:
          context: https://github.com/mm3818/Study_Companion/tree/main/app/frontend
          file: Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/study-companion-frontend:${{ github.run_id }}

  update-deployment:
    name: Update Deployment Manifest
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Deployment Image Tag
        run: |
          # Update your Helm values file (or other deployment manifest) with the new image tag
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' infra/helm/study-companion/values.yaml

      - name: Commit Updated Manifest
        run: |
          git config --local user.email "mm3818@srmist.edu.in"
          git config --local user.name "mm3818"
          git add infra/helm/study-companion/values.yaml
          git commit -m "Update image tag to ${{ github.run_id }}"
          git push